name: "Deploy Terraform Module"

on:
  push:
    branches:
      - main
      - develop  

jobs:
  deploy-terraform:
    uses: eduzuchetti/ez-devops-gh-actions/.github/workflows/pipeline-terraform-module.yml@main
    secrets: inherit
    with:
      sonar-scan: true
      terraform-version: 1.13.5
      unique-environment: true